#pragma once

#define MAX_LOADSTRING 100

#define WINDOW_WIDTH 640
#define WINDOW_HEIGHT 480

#define DEFAULT_ENEMY_SPEED 1
#define DEFAULT_PLAYER_SPEED 6
#define DEFAULT_BULLET_SPEED 4
#define DEFAULT_BULLET_SIZE 10
#define PLAYER_SIZE 45

#define DIFFICULTY_INCREASE_TIME 10000 //in ms
#define UPGRADE_TRESHOLD 1500
#define UPGRADE_INCREMENT 5

#define ENEMY_MAX_SIZE 100
#define ENEMY_MIN_SIZE 60
#define ENEMY_MIN_SPEED 1
#define ENEMY_SPAWN_RATE 50

#define BTN_HEIGHT 50
#define BTN_WIDTH 100
#define ID_BTN_START 999
#define ID_BTN_UPGRADE_BULLET_SIZE 998
#define ID_BTN_UPGRADE_BULLET_SPEED 997