#pragma once

#define ENEMY_MAX_SIZE 100
#define ENEMY_MIN_SIZE 60
#define ENEMY_MAX_SPEED 4
#define ENEMY_MIN_SPEED 1
#define ENEMY_SPAWN_RATE 50

#define MAX_LOADSTRING 100

#define WINDOW_WIDTH 640
#define WINDOW_HEIGHT 480

#define PLAYER_SPEED 4